---
title: "Martens: Pre-Print Paper Presentation"
format: 
  revealjs:
    theme: serif

---

## Data Driven Taxonomy for Antipsychotic Medication: A New Classification System

---
## Background

Why did they write this paper?
What was the need?
What did they hope to achieve?
What did they contribute to what is already known about categories of receptors?
---

## Method

---

## Four groups were defined:
---

## Group 1 <br> <br>
Muscarinic (M3-M5) receptor antagonism; Cholinergic and metabolic side effects.  
---
## Group 2 <br> <br> 
Dopamine (D2) partial agonism and adrenergic antagonism; Globally low side effect burden. 
---
## Group 3 <br> <br>
Serotonergic and dopaminergic antagonism; Globally moderate side effect burden.  
---
## Group 4 <br> <br>
Dopaminergic antagonism; Extrapyramidal and motor side effects. 
---
Groups 1 and 4 were more efficacious than clusters 2 and 3. The novel classification was superior to existing approaches when predicting side effects



---
## Conclusion 

Conclusions: A receptor affinity-based grouping not only reflects compound pharmacology but also detects meaningful clinical differences to a greater extent than existing approaches. The approach has the potential to benefit both patients and researchers by guiding treatment and informing drug development.

---
## How can we use this in our work?


---

